### ISSUE TITLE
https on labl.es

### ISSUE THREAD

**Issue by bhousel** [bhousel/svg-labels#1]
Should support https

**Comment by DenisCarriere** [comment]
Add http2 👍 

Since you're using already Nginx, you can use this as reference (uses LetsEncrypt + Nginx):

[**nginx.conf**](https://github.com/osmottawa/micro-data-service/blob/master/nginx/nginx.conf)
[**sites-available/default**](https://github.com/osmottawa/micro-data-service/blob/master/nginx/sites-available/default)

Use to be `A+` but now it's a `B` 😢  using [SSL Server Test](https://www.ssllabs.com/ssltest/analyze.html?d=data.osmcanada.com)

**Comment by bhousel** [comment]
I did this!  Thanks @DenisCarriere for the tip on Let's Encrypt, and I enabled http2 also.

I ended up using certbot [as mentioned here](https://letsencrypt.org/getting-started/) and it was really easy..

Also, I mostly followed [this guide](https://raymii.org/s/tutorials/Strong_SSL_Security_On_nginx.html) to comment out old ssl ciphers and update the DH parameters to a custom 4096 bit key.  (The only difference from the guide is that all of the ssl configurations should go into the letsencrypt include - `/etc/letsencrypt/options-ssl-nginx.conf `)

<img width="1077" alt="screenshot 2017-07-22 23 16 17" src="https://user-images.githubusercontent.com/38784/28496214-cb6f118c-6f33-11e7-873e-7daedb5dd393.png">

**Comment by DenisCarriere** [comment]
👍 @bhousel Awesome stuff! I'm glad you were able to enable SSL, ❤️ Let's Encrypt makes it really easy for developers to enable HTTPS now.
